/* ══════════════════════════════════════════════════════════════════
   LCDV CRM — clients-data.js
   ══════════════════════════════════════════════════════════════════
   INSTRUCTIONS D'INTÉGRATION :
   
   1. Ajouter dans index.html, AVANT la balise <script src="app.js"> :
      <script src="clients-data.js"></script>
   
   2. Dans app.js, supprimer ou vider la constante KML_CLIENTS existante
      (elle est remplacée par ce fichier)
   
   3. Dans loadState(), la ligne :
      clients = JSON.parse(JSON.stringify(KML_CLIENTS));
      continuera à fonctionner normalement.
   
   4. Optionnel — afficher le CA dans les cards clients :
      Dans renderClients(), après la ligne card-visit, ajouter :
      ${c.ca2026>0?`<div class="card-ca">CA 2026 : <strong>${c.ca2026.toLocaleString('fr-BE',{maximumFractionDigits:0})} €</strong></div>`:''}
   
   5. Optionnel — CSS à ajouter :
      .card-ca { font-size:12px; color:var(--text-3); margin-top:3px; }
      .card-ca strong { color:var(--accent); font-weight:600; }
   ══════════════════════════════════════════════════════════════════ */

// AUTO-GENERATED from Excel — do not edit manually
// Generated: 2026-06-08

const KML_CLIENTS = [
  {
    "id": 1,
    "societe": "Ambassador-Hôtel Bosten",
    "ville": "EUPEN",
    "contact": "",
    "canal": "",
    "categorie": "Hôtel / Autre",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 2,
    "societe": "Arnaud Schreiber",
    "ville": "WELKENRAEDT",
    "contact": "Arnaud SCHREIBER",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 3,
    "societe": "Atelier",
    "ville": "EUPEN",
    "contact": "Marc NUCHTERN",
    "canal": "Mail",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 1080.57,
    "ca2025": 3882.56,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 4,
    "societe": "Atelier 42",
    "ville": "THIMISTER",
    "contact": "Lucas PONCELET",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 4541.41,
    "ca2025": 10242.43,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 5,
    "societe": "Au 3 bis restaurant",
    "ville": "EUPEN",
    "contact": "Nico",
    "canal": "",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0.0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 6,
    "societe": "Au Bercail",
    "ville": "WELKENRAEDT",
    "contact": "François BILLET",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 704.18,
    "ca2025": 1180.69,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 7,
    "societe": "Au Bistronome",
    "ville": "DALHEM",
    "contact": "François BILLET",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 14227.66,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 8,
    "societe": "Au Coucou",
    "ville": "LA REID",
    "contact": "François BILLET",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 3599.6,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 9,
    "societe": "Au Clair Obscur",
    "ville": "VERVIERS",
    "contact": "François BILLET",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0.0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 10,
    "societe": "Au Murmure",
    "ville": "VERVIERS",
    "contact": "Nico",
    "canal": "",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 6998.82,
    "ca2025": 12247.61,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 11,
    "societe": "Au P'tit Marché",
    "ville": "LIMBOURG",
    "contact": "Nico",
    "canal": "",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 658.41,
    "ca2025": 495.21,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 12,
    "societe": "Au P'tit Marmiton",
    "ville": "VERVIERS",
    "contact": "Nico",
    "canal": "",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 589.1,
    "ca2025": 925.46,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 13,
    "societe": "Au P'tit Nico",
    "ville": "VERVIERS",
    "contact": "Nico",
    "canal": "",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 0.0,
    "ca2025": 886.24,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 14,
    "societe": "Au Petit Chef",
    "ville": "MALMEDY",
    "contact": "Nico",
    "canal": "",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 0,
    "ca2025": 1212.69,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 15,
    "societe": "Au Petit Clos",
    "ville": "HEUSY",
    "contact": "Nico",
    "canal": "",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 420.24,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 16,
    "societe": "Au Portail",
    "ville": "MOMALLE",
    "contact": "LEKEU",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 0.0,
    "ca2025": 5769.59,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 17,
    "societe": "Au Relais",
    "ville": "LAMBERMONT",
    "contact": "Christian KERN",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 10424.42,
    "ca2025": 24304.28,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 18,
    "societe": "Au Renouveau",
    "ville": "THIMISTER",
    "contact": "Dorian SCHOONBROODT",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 2336.99,
    "ca2025": 10935.76,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 19,
    "societe": "Au Repère Gourmand",
    "ville": "HOMBOURG",
    "contact": "Dorian SCHOONBROODT",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 1906.72,
    "ca2025": 5171.39,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 20,
    "societe": "Au Vi Houget",
    "ville": "VERVIERS",
    "contact": "",
    "canal": "",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 1159.71,
    "ca2025": 1088.27,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 21,
    "societe": "Au Vieil Aubel",
    "ville": "AUBEL",
    "contact": "",
    "canal": "",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 0.0,
    "ca2025": 2723.82,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 22,
    "societe": "Au Vieux Cerexhe",
    "ville": "PEPINSTER",
    "contact": "",
    "canal": "",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 17469.32,
    "ca2025": 45277.43,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 23,
    "societe": "Au Vieux Sart",
    "ville": "SART-LEZ-SPA",
    "contact": "Charlotte BERNARD",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 3313.13,
    "ca2025": 9596.26,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 24,
    "societe": "Aux Alentours",
    "ville": "VERVIERS",
    "contact": "Michael MISSIO",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 2905.75,
    "ca2025": 324.36,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 25,
    "societe": "Aux Deux Frères",
    "ville": "AUBEL",
    "contact": "Michael MISSIO",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 1835.98,
    "ca2025": 3490.85,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 26,
    "societe": "Aux Étangs",
    "ville": "HERVE",
    "contact": "Sophia THIRION",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 18924.46,
    "ca2025": 65535.05,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 27,
    "societe": "Azzurra Pizzeria",
    "ville": "HERVE",
    "contact": "Benjamin ABINET",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 124.98,
    "ca2025": 2005.31,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 28,
    "societe": "Bar@Pasta",
    "ville": "WELKENRAEDT",
    "contact": "Eric DEGENEFFE",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 29,
    "societe": "Bar à Bout des Charmilles",
    "ville": "OVIFAT",
    "contact": "Eric DEGENEFFE",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 6937.89,
    "ca2025": 18889.44,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 30,
    "societe": "Bella Vita",
    "ville": "AUBEL",
    "contact": "Bernard PLEYERS",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 1804.77,
    "ca2025": 5250.35,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 31,
    "societe": "Bien vivre et partager",
    "ville": "VISÉ",
    "contact": "Bernard PLEYERS",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 32,
    "societe": "Bilisse",
    "ville": "JALHAY",
    "contact": "Bernard PLEYERS",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 4302.34,
    "ca2025": 11116.25,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 33,
    "societe": "Bistronomie M",
    "ville": "WANZE",
    "contact": "Caro",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 2057.73,
    "ca2025": 4881.73,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 34,
    "societe": "Bonbon Caramel",
    "ville": "HEUSY",
    "contact": "Caro",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 1415.91,
    "ca2025": 8922.03,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 35,
    "societe": "Bonbon Caramel",
    "ville": "FLERON",
    "contact": "Sophie",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 1415.91,
    "ca2025": 8922.03,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 36,
    "societe": "Bonbon Caramel",
    "ville": "MALMEDY",
    "contact": "Caro",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 1415.91,
    "ca2025": 8922.03,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 37,
    "societe": "Bonni",
    "ville": "WELKENRAEDT",
    "contact": "Andy",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 2032.9,
    "ca2025": 1623.48,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 38,
    "societe": "Boucherie de la Platte",
    "ville": "BELLEVAUX",
    "contact": "Linda GEURTS",
    "canal": "SMS",
    "categorie": "Boucherie / Boulangerie",
    "statut": "Client",
    "ca2026": 0,
    "ca2025": 685.46,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 39,
    "societe": "Boucherie Geurts",
    "ville": "WELKENRAEDT",
    "contact": "Linda GEURTS",
    "canal": "SMS",
    "categorie": "Boucherie / Boulangerie",
    "statut": "Client",
    "ca2026": 181.15,
    "ca2025": 654.52,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 40,
    "societe": "Boucherie Gouder de Beauregard",
    "ville": "GEMMENICH",
    "contact": "Dany GOUDER DE BEAUREGARD",
    "canal": "WhatsApp",
    "categorie": "Boucherie / Boulangerie",
    "statut": "Client",
    "ca2026": 1319.8,
    "ca2025": 721.11,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 41,
    "societe": "Boucherie Porc Amarelle",
    "ville": "PLOMBIERES",
    "contact": "Muriel ROBROECKS",
    "canal": "WhatsApp",
    "categorie": "Boucherie / Boulangerie",
    "statut": "Client",
    "ca2026": 593.57,
    "ca2025": 1220.77,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 42,
    "societe": "Boucherie Renders",
    "ville": "LIMBOURG",
    "contact": "André RENDERS",
    "canal": "Messenger",
    "categorie": "Boucherie / Boulangerie",
    "statut": "Client",
    "ca2026": 0.0,
    "ca2025": 94.86,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 43,
    "societe": "Bowling67 - S'Pace",
    "ville": "LONTZEN",
    "contact": "Olivier RAUSCHEN",
    "canal": "Messenger",
    "categorie": "Drink / Cave",
    "statut": "Client",
    "ca2026": 1592.33,
    "ca2025": 4600.52,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 44,
    "societe": "Brasserie Central",
    "ville": "VERVIERS",
    "contact": "John MOMMER",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 356.5,
    "ca2025": 561.03,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 45,
    "societe": "Brasserie du Bernalmont",
    "ville": "LIEGE",
    "contact": "John MOMMER",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 794.58,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 46,
    "societe": "Brasserie L'Entracte WDT",
    "ville": "WELKENRAEDT",
    "contact": "John MOMMER",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 47,
    "societe": "Casino de Spa",
    "ville": "SPA",
    "contact": "Chouchou / Nathalie LINNERTZ",
    "canal": "Mail",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 5506.71,
    "ca2025": 15363.37,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 48,
    "societe": "Chamelon",
    "ville": "EUPEN",
    "contact": "Chouchou / Nathalie LINNERTZ",
    "canal": "Mail",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 49,
    "societe": "Chez Chouchou",
    "ville": "MALMEDY",
    "contact": "Chouchou / Nathalie LINNERTZ",
    "canal": "Mail",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 6368.41,
    "ca2025": 12502.74,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 50,
    "societe": "Chez Didier",
    "ville": "VERVIERS",
    "contact": "Constantinos DEMERTZIDIS",
    "canal": "",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 77.52,
    "ca2025": 346.48,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 51,
    "societe": "Chez Gary",
    "ville": "BASSENGE",
    "contact": "Jessica",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 3358.21,
    "ca2025": 7432.68,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 52,
    "societe": "Chez H",
    "ville": "VERVIERS",
    "contact": "Jessica",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 4764.08,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 53,
    "societe": "Chez Josephine",
    "ville": "WELKENRAEDT",
    "contact": "Jessica",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 54,
    "societe": "Chez M",
    "ville": "HERSTAL",
    "contact": "Jessica",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 6787.33,
    "ca2025": 11836.87,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 55,
    "societe": "Chez Marie",
    "ville": "VERVIERS",
    "contact": "Jessica",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 326.7,
    "ca2025": 2814.03,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 56,
    "societe": "Chez Maureen",
    "ville": "PEPINSTER",
    "contact": "Jessica",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 1346.97,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 57,
    "societe": "Chez Sarah",
    "ville": "VERVIERS",
    "contact": "Sarah RINGHOFFER",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 0,
    "ca2025": 7431.63,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 58,
    "societe": "Chez Vinc'e",
    "ville": "SPA",
    "contact": "Sarah RINGHOFFER",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 59,
    "societe": "Club des Cinq",
    "ville": "AUBEL",
    "contact": "Pierre REENAERS",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 9777.96,
    "ca2025": 20641.91,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 60,
    "societe": "Côté Comptoir by Sandroli",
    "ville": "WELKENRAEDT",
    "contact": "Pierre REENAERS",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 21095.31,
    "ca2025": 15864.72,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 61,
    "societe": "Côté Comptoir",
    "ville": "WELKENRAEDT",
    "contact": "Rob",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 62,
    "societe": "Cuisine Authentique",
    "ville": "CHAINEUX",
    "contact": "Emilie HARDIQUEST",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 11956.22,
    "ca2025": 28517.12,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 63,
    "societe": "Delicatess' Am Markt",
    "ville": "EUPEN",
    "contact": "Dominique",
    "canal": "Messenger",
    "categorie": "Drink / Cave",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0.0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 64,
    "societe": "De Mère en Fille",
    "ville": "VISÉ",
    "contact": "Cécile",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 9257.57,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 65,
    "societe": "Didier T Artisans Culinaires",
    "ville": "MALMEDY",
    "contact": "Cécile",
    "canal": "WhatsApp",
    "categorie": "Traiteur / Épicerie fine",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 66,
    "societe": "Domaine Bilstain",
    "ville": "BILSTAIN",
    "contact": "Cécile",
    "canal": "WhatsApp",
    "categorie": "Hôtel / Autre",
    "statut": "Client",
    "ca2026": 5433.51,
    "ca2025": 11868.59,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 67,
    "societe": "Dolce Vita",
    "ville": "SPA",
    "contact": "Dominique",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 68,
    "societe": "Drink Charlier Shop",
    "ville": "HERVE",
    "contact": "Dominique",
    "canal": "Messenger",
    "categorie": "Drink / Cave",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 69,
    "societe": "Drink Grooten",
    "ville": "WELKENRAEDT",
    "contact": "Dominique",
    "canal": "Messenger",
    "categorie": "Drink / Cave",
    "statut": "Client",
    "ca2026": 0.0,
    "ca2025": 5626.5,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 70,
    "societe": "Drive-In Andrien",
    "ville": "THEUX",
    "contact": "Dominique",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 71,
    "societe": "Einkaufen&Geniessen",
    "ville": "KRINKELT",
    "contact": "Valérie FANK",
    "canal": "Mail",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 0.0,
    "ca2025": 3222.74,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 72,
    "societe": "El Chicco by Caro",
    "ville": "VERVIERS",
    "contact": "Lazarine BECKERS",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 0,
    "ca2025": 302.44,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 73,
    "societe": "Elandeline",
    "ville": "WELKENRAEDT",
    "contact": "Lazarine BECKERS",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 1002.28,
    "ca2025": 1647.8,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 74,
    "societe": "Eli's Café",
    "ville": "AUBEL",
    "contact": "Lazarine BECKERS",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 75,
    "societe": "Épicur'Anne",
    "ville": "GRIVEGNEE",
    "contact": "Anne Pesesse",
    "canal": "Messenger",
    "categorie": "Drink / Cave",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 76,
    "societe": "Extra Time",
    "ville": "BATTICE",
    "contact": "Samuel HEMMER",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 1577.96,
    "ca2025": 5164.85,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 77,
    "societe": "Friterie Graffiti",
    "ville": "LONTZEN",
    "contact": "Muriel ROOGEMANS",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 502.34,
    "ca2025": 2146.41,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 78,
    "societe": "Friterie La Terrasse",
    "ville": "LAMBERMONT",
    "contact": "Muriel ROOGEMANS",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 288.8,
    "ca2025": 400.33,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 79,
    "societe": "Fromagerie Straet",
    "ville": "VERVIERS",
    "contact": "Muriel ROOGEMANS",
    "canal": "Messenger",
    "categorie": "Drink / Cave",
    "statut": "Client",
    "ca2026": 1567.26,
    "ca2025": 352.66,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 80,
    "societe": "Gare aux Goûts",
    "ville": "HOMBOURG",
    "contact": "Joël",
    "canal": "Whatsapp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 16854.73,
    "ca2025": 36038.69,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 81,
    "societe": "Goosse",
    "ville": "LIEGE",
    "contact": "Joël",
    "canal": "Whatsapp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 82,
    "societe": "Gorgées",
    "ville": "VERVIERS",
    "contact": "Joël",
    "canal": "Whatsapp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 83,
    "societe": "Grill de La Clouse",
    "ville": "AUBEL",
    "contact": "Jean GOIRE",
    "canal": "SMS",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 3664.95,
    "ca2025": 8044.39,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 84,
    "societe": "GUGA",
    "ville": "AUBEL",
    "contact": "Arnaud Van Melsen",
    "canal": "SMS",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 85,
    "societe": "Hôtel Ambassador Bosten",
    "ville": "MALMEDY",
    "contact": "Jean GOIRE",
    "canal": "SMS",
    "categorie": "Hôtel / Autre",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 86,
    "societe": "Hôtel du Moulin",
    "ville": "MALMEDY",
    "contact": "Jean GOIRE",
    "canal": "SMS",
    "categorie": "Hôtel / Autre",
    "statut": "Client",
    "ca2026": 0.0,
    "ca2025": 1452.17,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 87,
    "societe": "Hôtel Van der Valk",
    "ville": "VERVIERS",
    "contact": "Alex HEINEN",
    "canal": "Messenger",
    "categorie": "Hôtel / Autre",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0.0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 88,
    "societe": "Homestorys PGmbH",
    "ville": "EUPEN",
    "contact": "Alex HEINEN",
    "canal": "Messenger",
    "categorie": "Hôtel / Autre",
    "statut": "Client",
    "ca2026": 794.41,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 89,
    "societe": "Jungle Park",
    "ville": "LONTZEN",
    "contact": "Alex HEINEN",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 929.2,
    "ca2025": 946.93,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 90,
    "societe": "KERN'S FOODTRUCK & EVENT",
    "ville": "LAMBERMONT",
    "contact": "",
    "canal": "",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 91,
    "societe": "Koda",
    "ville": "VISE",
    "contact": "Joseph NYSSEN",
    "canal": "0493 50 88 21 / 0479 70 11 41",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 4750.91,
    "ca2025": 7718.73,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 92,
    "societe": "L'Arnica",
    "ville": "CRISNEE",
    "contact": "Sébastien DELATTRE",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 2604.05,
    "ca2025": 2706.6,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 93,
    "societe": "L'Entracte Verviers",
    "ville": "VERVIERS",
    "contact": "Sébastien DELATTRE",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 1631.46,
    "ca2025": 1171.51,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 94,
    "societe": "L'Entre D2ux",
    "ville": "GRIVEGNEE",
    "contact": "Sébastien DELATTRE",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 1889.75,
    "ca2025": 7519.69,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 95,
    "societe": "L'Entre-Potes",
    "ville": "HERBESTAL",
    "contact": "Sébastien DELATTRE",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 3800.35,
    "ca2025": 10484.63,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 96,
    "societe": "L'Épée Gourmande",
    "ville": "VERVIERS",
    "contact": "Léo/Merghim ZEEKOLI",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 11617.1,
    "ca2025": 31472.02,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 97,
    "societe": "L'Epicurien",
    "ville": "HERVE",
    "contact": "Sébastien BRELA",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 2034.97,
    "ca2025": 8481.29,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 98,
    "societe": "L'Obra",
    "ville": "BRA",
    "contact": "Raphael OUTMANNS",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 4535.72,
    "ca2025": 13094.56,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 99,
    "societe": "L'Officine",
    "ville": "EUPEN",
    "contact": "Raphael OUTMANNS",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 1017.96,
    "ca2025": 1387.28,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 100,
    "societe": "L'Usine",
    "ville": "DISON",
    "contact": "Raphael OUTMANNS",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 17596.07,
    "ca2025": 36032.89,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 101,
    "societe": "La Barbotte",
    "ville": "VERVIERS",
    "contact": "Achraf/Zouhair LARHOUASLI",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 9225.74,
    "ca2025": 31348.44,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 102,
    "societe": "La Belle Epoque",
    "ville": "SPA",
    "contact": "Achraf/Zouhair LARHOUASLI",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 0,
    "ca2025": 6143.52,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 103,
    "societe": "La Belle Maison",
    "ville": "SIPPENAEKEN",
    "contact": "Achraf/Zouhair LARHOUASLI",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 857.21,
    "ca2025": 1730.57,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 104,
    "societe": "La Bouchée d'Ailleurs",
    "ville": "VERVIERS",
    "contact": "Achraf/Zouhair LARHOUASLI",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 8368.98,
    "ca2025": 20576.61,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 105,
    "societe": "La Brasserie de Franchimont",
    "ville": "THEUX",
    "contact": "Laurent BRIXHE",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 2858.18,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 106,
    "societe": "La Brasserie des Etangs",
    "ville": "HERVE",
    "contact": "Laurent BRIXHE",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 13744.88,
    "ca2025": 36612.69,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 107,
    "societe": "La Brasserie des Thermes",
    "ville": "SPA",
    "contact": "Durim KRYEZI",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 0,
    "ca2025": 4636.71,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 108,
    "societe": "La Brasserie du 4009 by Pompon",
    "ville": "VERVIERS",
    "contact": "Maurane ROGGEMANS",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 0.0,
    "ca2025": 1190.08,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 109,
    "societe": "La Brasserie du Ciné",
    "ville": "VERVIERS",
    "contact": "Maurane ROGGEMANS",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 17148.58,
    "ca2025": 29461.27,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 110,
    "societe": "La Brasserie du Haras",
    "ville": "HEUSY",
    "contact": "Maurane ROGGEMANS",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 10925.4,
    "ca2025": 10859.61,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 111,
    "societe": "La Centrale Des Viandes",
    "ville": "LIEGE",
    "contact": "",
    "canal": "",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 112,
    "societe": "La Commanderie 7",
    "ville": "FOURON",
    "contact": "Vincent BALTUS",
    "canal": "SMS",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 1059.24,
    "ca2025": 4214.36,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 113,
    "societe": "La Couronne",
    "ville": "KAPEL",
    "contact": "Jérémy FINCK",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 21535.3,
    "ca2025": 45404.59,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 114,
    "societe": "La Crémaillère",
    "ville": "JALHAY",
    "contact": "Jérémy FINCK",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 115,
    "societe": "La Croustade",
    "ville": "VERVIERS",
    "contact": "Jérémy FINCK",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 0,
    "ca2025": 107.29,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 116,
    "societe": "La Papote",
    "ville": "THEUX",
    "contact": "Jérémy FINCK",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 3718.61,
    "ca2025": 1338.32,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 117,
    "societe": "La Pausa",
    "ville": "SPA",
    "contact": "Jérémy FINCK",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 9597.07,
    "ca2025": 29892.73,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 118,
    "societe": "La Plume",
    "ville": "SOUMAGNE",
    "contact": "Jérémy FINCK",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 119,
    "societe": "La Retenue",
    "ville": "VERVIERS",
    "contact": "Cyril DEGEE",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 7785.47,
    "ca2025": 19683.77,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 120,
    "societe": "La Table Rase",
    "ville": "JEHANSTER",
    "contact": "Julien BERNARD",
    "canal": "Téléphone",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 0.0,
    "ca2025": 513.01,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 121,
    "societe": "La Taverne du Perron",
    "ville": "STEMBERT",
    "contact": "Julien BERNARD",
    "canal": "Téléphone",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 2456.96,
    "ca2025": 8462.62,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 122,
    "societe": "La Véranda",
    "ville": "MORESNET",
    "contact": "Cynthia ROOGEMANS",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 6220.7,
    "ca2025": 15116.75,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 123,
    "societe": "La Vieille Vaisselle",
    "ville": "THIMISTER",
    "contact": "Cynthia ROOGEMANS",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 124,
    "societe": "Le Bar Fly",
    "ville": "SPA",
    "contact": "Vincent & Kelly",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 125,
    "societe": "Le Baron",
    "ville": "COO",
    "contact": "Nicolas ROCK",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 0.0,
    "ca2025": 1060.84,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 126,
    "societe": "Le Berry",
    "ville": "AUBEL",
    "contact": "Nicolas ROCK",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 21234.07,
    "ca2025": 18541.03,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 127,
    "societe": "Le Charlemagne",
    "ville": "VERVIERS",
    "contact": "Nicolas ROCK",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 3696.17,
    "ca2025": 2501.68,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 128,
    "societe": "Le Coq en Ville",
    "ville": "VERVIERS",
    "contact": "Nicolas ROCK",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 129,
    "societe": "Le Domaine des Hautes Fagnes",
    "ville": "OVIFAT",
    "contact": "Mathieu CIALONE",
    "canal": "Whatsapp",
    "categorie": "Hôtel / Autre",
    "statut": "Client",
    "ca2026": 6285.05,
    "ca2025": 16597.11,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 130,
    "societe": "Le Fourquet",
    "ville": "THIMISTER",
    "contact": "Joël",
    "canal": "Whatsapp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 6268.73,
    "ca2025": 15331.95,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 131,
    "societe": "Le Franc'off",
    "ville": "SPA",
    "contact": "Ludovic COMPÈRE",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0.0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 132,
    "societe": "Le Jardin des Elfes",
    "ville": "SPA",
    "contact": "Ludovic COMPÈRE",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 3783.1,
    "ca2025": 20777.46,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 133,
    "societe": "Le Macadam",
    "ville": "EUPEN",
    "contact": "Ludovic COMPÈRE",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0.0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 134,
    "societe": "Le Ménobu",
    "ville": "THEUX",
    "contact": "Ludovic COMPÈRE",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 855.78,
    "ca2025": 3765.83,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 135,
    "societe": "Le Midi",
    "ville": "PETIT-RECHAIN",
    "contact": "Ludovic COMPÈRE",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 8945.1,
    "ca2025": 425.86,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 136,
    "societe": "Le Palmares",
    "ville": "SPA",
    "contact": "",
    "canal": "",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 137,
    "societe": "Le Patch",
    "ville": "VERVIERS",
    "contact": "",
    "canal": "",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 0,
    "ca2025": 98.22,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 138,
    "societe": "Le Roannay",
    "ville": "STAVELOT",
    "contact": "David LINDT",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 5273.61,
    "ca2025": 14104.92,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 139,
    "societe": "Le Solera",
    "ville": "WELKENRAEDT",
    "contact": "Pierre DUBOIS",
    "canal": "-",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 1829.28,
    "ca2025": 3625.77,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 140,
    "societe": "Le Tigre",
    "ville": "VERVIERS",
    "contact": "Jean-Louis BERNARD",
    "canal": "Téléphone",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 1846.54,
    "ca2025": 3247.68,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 141,
    "societe": "Le Tonnelet",
    "ville": "NIVEZE",
    "contact": "Jean-Louis BERNARD",
    "canal": "Téléphone",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 2968.03,
    "ca2025": 1754.4,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 142,
    "societe": "Les Fines Gueules",
    "ville": "HERVE",
    "contact": "Flavio SANTOS MARTINS",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 31129.69,
    "ca2025": 80500.02,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 143,
    "societe": "Les Montagnards",
    "ville": "OLNE",
    "contact": "Valérie DANSE",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 25076.48,
    "ca2025": 25426.46,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 144,
    "societe": "Les Thermes de Spa",
    "ville": "SPA",
    "contact": "Valérie DANSE",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 15148.37,
    "ca2025": 54068.78,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 145,
    "societe": "Les Toqués Gourmands",
    "ville": "EUPEN",
    "contact": "Fanny GUSTIN",
    "canal": "Téléphone",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 155.03,
    "ca2025": 1005.5,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 146,
    "societe": "Level 5",
    "ville": "EUPEN",
    "contact": "Fanny GUSTIN",
    "canal": "Téléphone",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 147,
    "societe": "Ma Cuisine",
    "ville": "HACCOURT",
    "contact": "Guy DUYSENS",
    "canal": "Téléphone",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 148,
    "societe": "Maison Blanche",
    "ville": "LONTZEN",
    "contact": "Guy DUYSENS",
    "canal": "Téléphone",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 149,
    "societe": "Maison Charlemagne",
    "ville": "KELMIS",
    "contact": "Guy DUYSENS",
    "canal": "Téléphone",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 2230.96,
    "ca2025": 8212.67,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 150,
    "societe": "Maison Duysens",
    "ville": "WELKENRAEDT",
    "contact": "Guy DUYSENS",
    "canal": "Téléphone",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 337.5,
    "ca2025": 1706.48,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 151,
    "societe": "Maison Fagne",
    "ville": "MALMEDY",
    "contact": "Guy DUYSENS",
    "canal": "Téléphone",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 5871.1,
    "ca2025": 3411.98,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 152,
    "societe": "Manoir de Lébiole",
    "ville": "SPA",
    "contact": "Maxime",
    "canal": "Messenger",
    "categorie": "Hôtel / Autre",
    "statut": "Client",
    "ca2026": 0.0,
    "ca2025": 17119.73,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 153,
    "societe": "Marco Brasserie Pizzeria",
    "ville": "HEUSY",
    "contact": "Maxime",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 1900.52,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 154,
    "societe": "Mosa Passion",
    "ville": "ENGIS",
    "contact": "Maxime",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 9465.38,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 155,
    "societe": "My Hotel by Intermills",
    "ville": "MALMEDY",
    "contact": "David LINDT",
    "canal": "Mail",
    "categorie": "Hôtel / Autre",
    "statut": "Client",
    "ca2026": 9303.95,
    "ca2025": 21382.02,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 156,
    "societe": "O Bois de la Julienne",
    "ville": "VISÉ",
    "contact": "Annick CHRISTIAENS",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 157,
    "societe": "Opcanner Anker",
    "ville": "RIEMST",
    "contact": "Annick CHRISTIAENS",
    "canal": "WhatsApp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 0,
    "ca2025": 2503.16,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 158,
    "societe": "PamPam",
    "ville": "VISÉ",
    "contact": "Alex  BRANA-AZCONA",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 0,
    "ca2025": 229.51,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 159,
    "societe": "Piazza Cucina",
    "ville": "THEUX",
    "contact": "Chantal GEHLEN",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 928.76,
    "ca2025": 1818.62,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 160,
    "societe": "Pizza Kapella",
    "ville": "WELKENRAEDT",
    "contact": "Chantal GEHLEN",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 0,
    "ca2025": 17.51,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 161,
    "societe": "Pizzeria Antica",
    "ville": "SART-LEZ-SPA",
    "contact": "Charlotte BERNARD",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 2162.91,
    "ca2025": 5485.44,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 162,
    "societe": "Pizzeria Sangio",
    "ville": "DOLHAIN",
    "contact": "Charlotte BERNARD",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 3643.29,
    "ca2025": 490.7,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 163,
    "societe": "Poulette",
    "ville": "RETINNE",
    "contact": "Lionel JOHNEN",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 7104.16,
    "ca2025": 6750.69,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 164,
    "societe": "Pub Grain d'Orge",
    "ville": "PLOMBIERES",
    "contact": "Lionel JOHNEN",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 19389.55,
    "ca2025": 42394.78,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 165,
    "societe": "Raph Cook's",
    "ville": "AUBEL",
    "contact": "Florent DECKER",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 12334.54,
    "ca2025": 30862.29,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 166,
    "societe": "Restaurant Le 4860",
    "ville": "PEPINSTER",
    "contact": "Florent DECKER",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 167,
    "societe": "Royale Etoile Elsautoise",
    "ville": "ELSAUTE",
    "contact": "DEMONCEAU",
    "canal": "Tel",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 185.12,
    "ca2025": 59.8,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 168,
    "societe": "Royal Football Club WDT",
    "ville": "WELKENRAEDT",
    "contact": "Albert HENDRICK",
    "canal": "Mail",
    "categorie": "Drink / Cave",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 169,
    "societe": "Royal Football Club Malmundaria",
    "ville": "MALMEDY",
    "contact": "Albert HENDRICK",
    "canal": "Mail",
    "categorie": "Drink / Cave",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 170,
    "societe": "RTC Belle-Vue",
    "ville": "WELKENRAEDT",
    "contact": "Eric REYNIERS",
    "canal": "Whatsapp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 3635.01,
    "ca2025": 7541.36,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 171,
    "societe": "Seventy",
    "ville": "MALMEDY",
    "contact": "Caro & Eric CHARLIE",
    "canal": "Mail",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 924.8,
    "ca2025": 5831.08,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 172,
    "societe": "Sirop Charlier",
    "ville": "HENRI-CHAPELLE",
    "contact": "Caro & Eric CHARLIE",
    "canal": "Mail",
    "categorie": "Drink / Cave",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 173,
    "societe": "Source de la Géronstère",
    "ville": "SPA",
    "contact": "Caro & Eric CHARLIE",
    "canal": "Mail",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0.0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 174,
    "societe": "Sucré Salé",
    "ville": "EUPEN",
    "contact": "Marc VLUGGEN",
    "canal": "Whatsapp",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 4592.06,
    "ca2025": 5013.96,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 175,
    "societe": "Swing & Saveurs",
    "ville": "HENRI-CHAPELLE",
    "contact": "Caro & Eric CHARLIE",
    "canal": "Mail",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 21223.08,
    "ca2025": 68422.5,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 176,
    "societe": "Take-Five",
    "ville": "AMBLEVE",
    "contact": "Jean-Marc LAMBIET",
    "canal": "tel",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 177,
    "societe": "Taverne Le Parc",
    "ville": "WELKENRAEDT",
    "contact": "Jean-Marc LAMBIET",
    "canal": "tel",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 6591.7,
    "ca2025": 16085.17,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 178,
    "societe": "Tel Père Telles Filles",
    "ville": "HERVE",
    "contact": "Stéphane HERZET",
    "canal": "mail",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 179,
    "societe": "Temps Libre",
    "ville": "WELKENRAEDT",
    "contact": "Stéphane HERZET",
    "canal": "mail",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 736.68,
    "ca2025": 1390.63,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 180,
    "societe": "The Swing",
    "ville": "HEUSY",
    "contact": "Stéphane HERZET",
    "canal": "mail",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 0,
    "ca2025": 13671.43,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 181,
    "societe": "Verviers Indoor Games Center",
    "ville": "VERVIERS",
    "contact": "Vincent & Kelly",
    "canal": "Messenger",
    "categorie": "Drink / Cave",
    "statut": "Client",
    "ca2026": 1141.18,
    "ca2025": 4101.18,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 182,
    "societe": "VIKE",
    "ville": "BAELEN",
    "contact": "Vincent & Kelly",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Prospect",
    "ca2026": 0,
    "ca2025": 0,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 183,
    "societe": "Vita Bella",
    "ville": "LAMBERMONT",
    "contact": "Vincent & Kelly",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 1733.44,
    "ca2025": 2055.11,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 184,
    "societe": "Wel Padel",
    "ville": "WELKENRAEDT",
    "contact": "Annick DODEMONT",
    "canal": "Messenger",
    "categorie": "Drink / Cave",
    "statut": "Client",
    "ca2026": 13745.82,
    "ca2025": 5361.54,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  },
  {
    "id": 185,
    "societe": "Zum Stiefel",
    "ville": "EUPEN",
    "contact": "Annick DODEMONT",
    "canal": "Messenger",
    "categorie": "Restaurant / Brasserie",
    "statut": "Client",
    "ca2026": 2122.13,
    "ca2025": 5498.94,
    "comm": "",
    "produits": [],
    "lat": null,
    "lng": null,
    "notes": "",
    "tel": "",
    "email": ""
  }
];

/* ── Helpers ──────────────────────────────────────────────────── */

function getTopClients(year, limit) {
  year = year || 2026;
  limit = limit || 15;
  var field = year === 2026 ? 'ca2026' : 'ca2025';
  return clients.slice().filter(function(c){ return c[field] > 0; })
    .sort(function(a,b){ return b[field] - a[field]; })
    .slice(0, limit);
}

function totalCA(year) {
  var field = (year || 2026) === 2026 ? 'ca2026' : 'ca2025';
  return clients.reduce(function(sum,c){ return sum + (c[field]||0); }, 0);
}

function clientsToRelaunch() {
  return clients.filter(function(c){ return !c.ca2026 && !c.ca2025 && c.statut !== 'Inactif'; });
}
